services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - baseball-net

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - baseball-net
    command: >
      bash -c "rm -rf /var/lib/postgresql/data/* && docker-entrypoint.sh postgres"

  backend:
    build: 
      context: ./server
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      - DB_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - postgres
      - ollama
    networks:
      - baseball-net
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./server:/app

  frontend:
    build:
      context: ./client
    environment:
      - VITE_API_URL=http://backend:8000
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - baseball-net

volumes:
  postgres_data:
  ollama_data:

networks:
  baseball-net: